"""Finite simplicial complexes."""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations
from typing import Iterable

from fastop.cohomology import PrimeFieldCohomology

Simplex = tuple[int, ...]


def _normalize_simplex(simplex: Iterable[int]) -> Simplex:
    vertices = tuple(sorted(simplex))
    if len(vertices) != len(set(vertices)):
        raise ValueError("simplices cannot contain repeated vertices")
    return vertices


@dataclass(frozen=True)
class SimplicialComplex:
    """A finite abstract simplicial complex generated by its facets."""

    facets: frozenset[Simplex]

    def __init__(self, facets: Iterable[Iterable[int]]):
        normalized = frozenset(_normalize_simplex(facet) for facet in facets)
        if not normalized:
            raise ValueError("a simplicial complex needs at least one facet")
        if any(not facet for facet in normalized):
            raise ValueError("facets must be non-empty")
        object.__setattr__(self, "facets", normalized)
        object.__setattr__(self, "_faces_by_dimension", self._build_faces())

    @classmethod
    def from_facets(cls, facets: Iterable[Iterable[int]]) -> "SimplicialComplex":
        """Create a complex from maximal or non-maximal listed simplices."""
        return cls(facets)

    @property
    def dimension(self) -> int:
        """Return the largest simplex dimension."""
        return max(self._faces_by_dimension)

    @property
    def vertices(self) -> tuple[int, ...]:
        """Return the vertices in increasing order."""
        return tuple(sorted({vertex for facet in self.facets for vertex in facet}))

    @property
    def supports_vertex_algorithms(self) -> bool:
        """Return whether cells carry globally comparable vertex sets."""
        return True

    def faces(
        self, dimension: int | None = None
    ) -> dict[int, frozenset[Simplex]] | frozenset[Simplex]:
        """Return faces, either all by dimension or in one dimension."""
        if dimension is None:
            return dict(self._faces_by_dimension)
        return self._faces_by_dimension.get(dimension, frozenset())

    def cells(
        self, dimension: int | None = None
    ) -> dict[int, frozenset[Simplex]] | frozenset[Simplex]:
        """Return simplices through the common finite-cell interface."""
        return self.faces(dimension)

    def face(self, degree: int, simplex: Simplex, index: int) -> Simplex:
        """Return the ``index``-th face of one simplex."""
        return simplex[:index] + simplex[index + 1 :]

    def restrict(
        self,
        degree: int,
        simplex: Simplex,
        positions: tuple[int, ...],
    ) -> Simplex:
        """Restrict a simplex to the listed local vertex positions."""
        return tuple(simplex[index] for index in positions)

    def as_delta_complex(self):
        """Return the same realization encoded only by face maps."""
        from fastop.delta_complex import DeltaComplex

        return DeltaComplex.from_simplicial_complex(self)

    def cohomology(
        self,
        p: int = 2,
        *,
        reduced: bool = False,
        convention: int = 1,
    ) -> PrimeFieldCohomology:
        """Return mod-``p`` cohomology with a chosen basis.
        """
        return PrimeFieldCohomology(self, p=p, reduced=reduced, convention=convention)

    def suspension(self, times: int = 1) -> "SimplicialComplex":
        """Return an iterated simplicial suspension.

        Each suspension is the join with a new zero-sphere.  New vertices are
        assigned consecutive labels above the largest label already present.
        """
        if not isinstance(times, int) or isinstance(times, bool):
            raise TypeError("times must be an integer")
        if times < 0:
            raise ValueError("times must be nonnegative")

        answer = self
        for _ in range(times):
            left = max(answer.vertices) + 1
            right = left + 1
            answer = SimplicialComplex(
                [facet + (left,) for facet in answer.facets]
                + [facet + (right,) for facet in answer.facets]
            )
        return answer

    def _build_faces(self) -> dict[int, frozenset[Simplex]]:
        faces: dict[int, set[Simplex]] = {}
        for facet in self.facets:
            for size in range(1, len(facet) + 1):
                dimension = size - 1
                faces.setdefault(dimension, set()).update(combinations(facet, size))
        return {dimension: frozenset(sorted(values)) for dimension, values in faces.items()}
